github:
  user: "github-actions[bot]"
  email: "41898282+github-actions[bot]@users.noreply.github.com"
  username: "UPDATECLI_GITHUB_ACTOR"
  token: "UPDATECLI_GITHUB_TOKEN"
  repository: "image-build-node-feature-discovery"
  branch: "pin-nfd-v0.15.x"
  owner: "mgfritch"
